from termcolor import colored

settlements_positions = list("abcdefghijklmnopqrstuvwxyz1ABCDEFGHIJKLMNOPQRSTUVWXYZ2")
settlements_icon = colored("Δ", "yellow", attrs=["bold"])
tile_images_path = "tiles"

resources_map = {
    "wo": {"text": "Wood ", "color": "green", "board_color": "dark green"},
    "b": {"text": "Brick", "color": "red", "board_color": "brown"},
    "o": {"text": " Ore ", "color": "dark_grey", "board_color": "grey"},
    "s": {"text": "Sheep", "color": "light_green", "board_color": "light green"},
    "w": {"text": "Wheat", "color": "yellow", "board_color": "yellow"},
    "r": {"text": "Empty", "color": "white", "board_color": "beige"},
}

dice_probability = {
    0: (0.0, 0, None),
    2: (0.028, 1, "red"),
    3: (0.056, 2, "red"),
    4: (0.083, 3, "yellow"),
    5: (0.111, 4, "yellow"),
    6: (0.139, 5, "green"),
    7: (0.167, 6, "green"),
    8: (0.139, 5, "green"),
    9: (0.111, 4, "yellow"),
    10: (0.083, 3, "yellow"),
    11: (0.056, 2, "red"),
    12: (0.028, 1, "red"),
}

indexes = {
    "a": [1],
    "b": [1],
    "c": [1, 2],
    "d": [2],
    "e": [2, 3],
    "f": [3],
    "g": [3],
    "h": [4],
    "i": [1, 4],
    "j": [1, 4, 5],
    "k": [1, 2, 5],
    "l": [2, 5, 6],
    "m": [2, 3, 6],
    "n": [3, 6, 7],
    "o": [3, 7],
    "p": [7],
    "q": [8],
    "r": [4, 8],
    "s": [4, 8, 9],
    "t": [4, 5, 9],
    "u": [5, 9, 10],
    "v": [5, 6, 10],
    "w": [6, 10, 11],
    "x": [6, 7, 11],
    "y": [7, 11, 12],
    "z": [7, 12],
    "1": [12],
    "A": [8],
    "B": [8, 13],
    "C": [8, 9, 13],
    "D": [9, 13, 14],
    "E": [9, 10, 14],
    "F": [10, 14, 15],
    "G": [10, 11, 15],
    "H": [11, 15, 16],
    "I": [11, 12, 16],
    "J": [12, 16],
    "K": [12],
    "L": [13],
    "M": [13, 17],
    "N": [13, 14, 17],
    "O": [14, 17, 18],
    "P": [14, 15, 18],
    "Q": [15, 18, 19],
    "R": [15, 16, 19],
    "S": [16, 19],
    "T": [16],
    "U": [17],
    "V": [17],
    "W": [17, 18],
    "X": [18],
    "Y": [18, 19],
    "Z": [19],
    "2": [19],
}

adjacent_settlement_positions = {
    "a": "bi",
    "b": "aci",
    "c": "bdk",
    "d": "ce",
    "e": "dfm",
    "f": "eg",
    "g": "fo",
    "h": "ir",
    "i": "ahj",
    "j": "ikt",
    "k": "cjl",
    "l": "kmv",
    "m": "eln",
    "n": "mox",
    "o": "gnp",
    "p": "oz",
    "q": "Ar",
    "r": "hqs",
    "s": "Crt",
    "t": "jsu",
    "u": "Etv",
    "v": "luw",
    "w": "Gvx",
    "x": "nwy",
    "y": "Ixz",
    "z": "1py",
    "1": "Kz",
    "A": "Bq",
    "B": "ACL",
    "C": "BDs",
    "D": "CEN",
    "E": "DFu",
    "F": "EGP",
    "G": "FHw",
    "H": "GIR",
    "I": "HJy",
    "J": "IKT",
    "K": "1J",
    "L": "BM",
    "M": "LNU",
    "N": "DMO",
    "O": "NPW",
    "P": "FOQ",
    "Q": "PRY",
    "R": "GHS",
    "S": "2RT",
    "T": "JS",
    "U": "MV",
    "V": "UW",
    "W": "OVX",
    "X": "WY",
    "Y": "QXZ",
    "Z": "2Y",
    "2": "SZ",
}
